ignore_theme_config: true
show_dir_listing: true
name: sa test catalog
title: null
theme: null

defaults:
  - scope:
      path: "ak-catalog"
    values:
      json: false
      sa-catalog: true

  - scope:
      path: "test-waf"
    values:
      json: false
      sa-catalog: true

  - scope:
      path: "test3"
    values:
      sa-catalog: false
      json: true

  - scope:
      path: "sb-projects"
    values:
      warehouse: true

  - scope:
      path: "gulfcoast-proj"
    values:
      warehouse: true
