ignore_theme_config: true
show_dir_listing: true
name: sa test catalog
title: null
theme: null

defaults:
  - scope:
      path: "test-waf"
    values:
      json: true

  - scope:
      path: "test3"
    values:
      sa-catalog: true
